name: continuousdelivery

on: push

defaults:
  run:
    working-directory: src/terraform

jobs:
  tfPlan:
    runs-on: ubuntu-latest
    name: Generate Plan
    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29

      - name: Terraform Init
        env:
          TF_CLI_ARGS_init: "-input=false -backend=true -backend-config=prod.stage"
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan
